CREATE DATABASE SHOPPING;
SHOW DATABASES;
USE SHOPPING;
CREATE TABLE USER(
	UIDX 		VARCHAR(12) 	PRIMARY KEY,
	UID 		VARCHAR(15) 	NOT NULL,
	UPW 		VARCHAR(15) 	NOT NULL,
	UNAME 		VARCHAR(21) 	NOT NULL,
	UBIRTH 		DATE 			NOT NULL,
	UPHONE 		VARCHAR(20) 	NOT NULL,
	UADDRESS 	VARCHAR(200),
	UADDRESSD 	VARCHAR(100),
	UEMAIL 		VARCHAR(100),
	UINSERTDATE DATETIME 		NOT NULL,
	UUPDATEDATE DATETIME 		NOT NULL,
	UDELETEYN 	VARCHAR(1) 		NOT NULL,
	UGRADE 		VARCHAR(1) 		NOT NULL,
    UPOST		VARCHAR(5)		NOT NULL
); 


SELECT * FROM USER;

CREATE TABLE PRODUCT(
	PIDX       	VARCHAR(12)    	PRIMARY KEY,   -- 상품일련번호
    PNAME       VARCHAR(150)    NOT NULL,      -- 상품명
    PPRICE      INT(8)          NOT NULL,      -- 상품가격
    PSTAR       VARCHAR(1)      NOT NULL,      -- 별점
    PDETAIL     TEXT         	NOT NULL,      -- 상세정보
    PCATEGORY   VARCHAR(100)   	NOT NULL,      -- 카테고리
    PIMAGE      VARCHAR(200)   	NOT NULL,      -- 상품 이미지
    PINSERTDATE DATETIME      	NOT NULL,      -- 상품 등록일
    PUPDATEDATE DATETIME      	NOT NULL      -- 상품 수정일
);

SELECT * FROM PRODUCT;

CREATE TABLE COMMENT (
    CIDX       		VARCHAR(12) 	PRIMARY KEY, -- 상품평 일련번호
    PIDX       		VARCHAR(12)		NOT NULL, -- 상품 번호 (외래키)
    UIDX       		VARCHAR(15) 	NOT NULL, -- 회원 번호 (외래키)
    CCONTENT      	VARCHAR(9000), -- 코멘트 내용
    CSTAR         	VARCHAR(1) 		NOT NULL, -- 별점
    CDELETEYN      	VARCHAR(1) 		NOT NULL DEFAULT 'Y', -- 삭제 여부 (Y/N)
    CININSERTDATE 	DATETIME 		NOT NULL, -- 등록일
    CUPDATEDATE   	DATETIME 		NOT NULL, -- 수정일
	FOREIGN KEY (PIDX) REFERENCES PRODUCT(PIDX), -- 상품 테이블과의 외래키 연결
	FOREIGN KEY (UIDX) REFERENCES USER(UIDX) -- 회원 테이블과의 외래키 연결 (가정)
); 

SELECT * FROM  COMMENT;

DROP TABLE COMMENT;
DROP TABLE USER;
DROP TABLE PRODUCT;

show tables;

